[project]
name = "hiv-program-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic==1.13.1",
    "annotated-types==0.6.0",
    "anyio==4.2.0",
    "bcrypt==4.1.2",
    "certifi==2024.12.14",
    "click==8.1.7",
    "dnspython==2.7.0",
    "ecdsa==0.18.0",
    "email-validator==2.2.0",
    "fastapi==0.115.6",
    "fastapi-cli==0.0.7",
    "greenlet==3.0.3",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httptools==0.6.4",
    "httpx==0.28.1",
    "idna==3.6",
    "jinja2==3.1.3",
    "mako==1.3.2",
    "markdown-it-py==3.0.0",
    "markupsafe==2.1.5",
    "mdurl==0.1.2",
    "passlib==1.7.4",
    "psycopg2-binary==2.9.9",
    "pyasn1==0.5.1",
    "pydantic==2.6.0",
    "pydantic-core==2.16.1",
    "pydantic-settings==2.1.0",
    "pygments==2.18.0",
    "python-dotenv==1.0.1",
    "python-jose==3.3.0",
    "python-multipart==0.0.7",
    "pyyaml==6.0.2",
    "rich==13.9.4",
    "rich-toolkit==0.12.0",
    "rsa==4.9",
    "shellingham==1.5.4",
    "six==1.16.0",
    "sniffio==1.3.0",
    "sqladmin==0.16.0",
    "sqlalchemy==2.0.25",
    "sqlmodel==0.0.14",
    "starlette==0.41.3",
    "typer==0.15.1",
    "typing-extensions==4.12.2",
    "uvicorn==0.27.0.post1",
    "watchfiles==1.0.3",
    "websockets==14.1",
    "wtforms==3.1.2",
]
